version: '3.4'

services:
    cvwebapi:
        build:
            context: ./CvWebApi
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
            - "8081:8081"
        depends_on:
            - sqlserver
        environment:
            - ASPNETCORE_ENVIROMENT=Development
        networks:
            - cvnetwork
        restart: on-failure
    sqlserver:
        image: mcr.microsoft.com/mssql/server:2022-latest
        environment:
            SA_PASSWORD: "Password12345!"
            ACCEPT_EULA: "Y"
        ports:
            - "1433:1433"
        volumes:
            - sqlvolume:/var/opt/mssql
        networks:
            - cvnetwork

networks:
    cvnetwork:

volumes:
    sqlvolume:    